version: "3.9"

services:
    catalogue-service:
        container_name: cbooks_catalogue
        hostname: catalogue
        build:
            context: ./catalogue-service
        ports:
            - 5053:5003  # host:container ${PORT}
        networks:
            - cbooks_net
        depends_on: 
            - catalogue-db

    catalogue-db:
        image: postgres:13-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin123
          - POSTGRES_DB=cool_books_catalogue_db
        ports: 
          - 15432:5432
        networks:
          - cbooks_net

volumes:
    postgres_data:

networks:
    cbooks_net:
        external:
            name: coolbooks_cbooks_net 

        
