version: "3.9"

services:
    ctlg:
        container_name: cbooks_catalogue
        hostname: catalogue
        build:
            context: .
        ports:
            - 5053:5003 
        networks:
            - books_net
        depends_on: 
            - catalogue-db
        restart: "unless-stopped"

    catalogue-db:
        image: postgres:13-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file: database.conf
        ports: 
          - 25432:5432
        networks:
          - books_net

volumes:
    postgres_data:

networks:
    books_net:
        external:
            name: cbooks_net


        

        
