version: "3.9"

services:
    mp-service:
        container_name: cbooks_market_place
        hostname: market-place
        build:
            context: .
        ports:
           - 5052:5002  # host:container  
        networks:
            - mbooks
        depends_on: 
            - market-db
        restart: "unless-stopped"

    market-db:
        image: postgres:13-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file: database.conf
        ports: 
          - 35432:5432
        networks:
          - mbooks



volumes:
    postgres_data:

networks:
    mbooks:
        external:
            name: cbooks_net

        

        
        
                
        
                
        